name: Update Package Versions

on:
  push:
    branches:
      - main

jobs:
  update-requirements:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Update Requirements
        run: |
          current_requirements=$(cat requirements.txt)
          
         
          while IFS= read -r line; do
           
            package_name=$(echo "$line" | cut -d'==' -f1)
            package_version=$(echo "$line" | cut -d'==' -f2)
            
            
            if [[ "$package_version" == "old" ]]; then
              
              pip install --upgrade "$package_name"
            fi
          done <<< "$current_requirements"

          
          pip freeze > requirements.txt

      - name: Commit Changes
        run: |
          git add requirements.txt
          git commit -m "Update package versions"
          git push
