name: Update Package Versions

on:
  push:
    branches:
      - main

jobs:
  update-requirements:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Update Package Versions
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt --upgrade
          git config --global user.name "Your Name"
          git config --global user.email "youremail@example.com"
          git checkout main
          git add requirements.txt
          git commit -m "Update package versions"
          git push
